version: '3.5'

services:
  compiler:
    build: .
    environment:
      # to install dependencies in the project, instead of user wide
      - CARGO_HOME=/app/.cargo
    volumes:
      - ".:/app"
    working_dir: /app
    command: "make build"

  devserver:
    image: node:9-slim
    command: npm run serve
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - 8080:8080
